[tool.poetry]
name = "popcorn-meter"
packages = [
    { include = "popcorn_meter" },
]
version = "2.4.2"
description = "A Streamlit app for movie discovery, watchlists, and recommendations."
authors = ["Ethar Ali <ethassan@users.noreply.github.com>", "kosar Emazahery  <kosarem@users.noreply.github.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0.0"
streamlit = "^1.54.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.4.0"
mypy = "^1.10.1"
poethepoet = "^0.37.0"
poetry = "^1.8.3"
pytest = "^8.2.2"
ruff = "^0.13.2"
types-requests = "^2.32.4.20260107"

[tool.poe.tasks]
test = "python -m pytest -v tests"
coverage = "coverage run -m pytest tests"
coverage-report = "coverage report -m"
coverage-html = "coverage html"
mypy = "mypy popcorn_meter tests"
ruff-check = "ruff check popcorn_meter tests"
static-checks = ["mypy", "ruff-check"]
format = "ruff format popcorn_meter tests"
compile = "python -m compileall popcorn_meter tests"

[tool.poetry.scripts]
popcorn-meter = "popcorn_meter.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi-test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"

[tool.mypy]
ignore_missing_imports = true

[tool.coverage.run]
omit = [
    "popcorn_meter/ui/*",
]